package sourceloc

import (
	"os"
	"path/filepath"
	"reflect"
	"runtime"
	"sort"
	"strings"
	"testing"
)

// writeFile writes content to root/relPath, creating intermediate dirs as
// needed. Fails the test on any I/O error so callers can assume success.
func writeFile(t *testing.T, root, relPath, content string) string {
	t.Helper()
	full := filepath.Join(root, filepath.FromSlash(relPath))
	if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
		t.Fatalf("mkdir %s: %v", filepath.Dir(full), err)
	}
	if err := os.WriteFile(full, []byte(content), 0o644); err != nil {
		t.Fatalf("write %s: %v", full, err)
	}
	return full
}

// goStub is a minimal valid .go file body. Content does not matter for the
// walker — only file name, dir position, and (for IsGenerated) first lines.
const goStub = "package p\n"

func TestWalkGoFiles_ReturnsAllGoFiles(t *testing.T) {
	root := t.TempDir()
	a := writeFile(t, root, "a.go", goStub)
	b := writeFile(t, root, "sub/b.go", goStub)
	c := writeFile(t, root, "sub/nested/c.go", goStub)

	got, err := WalkGoFiles(root)
	if err != nil {
		t.Fatalf("WalkGoFiles: %v", err)
	}
	want := []string{a, b, c}
	sort.Strings(want)
	if !reflect.DeepEqual(got, want) {
		t.Errorf("files mismatch:\n got %v\nwant %v", got, want)
	}
}

func TestWalkGoFiles_SkipsTestFiles(t *testing.T) {
	root := t.TempDir()
	a := writeFile(t, root, "a.go", goStub)
	writeFile(t, root, "a_test.go", goStub)

	got, err := WalkGoFiles(root)
	if err != nil {
		t.Fatalf("WalkGoFiles: %v", err)
	}
	if !reflect.DeepEqual(got, []string{a}) {
		t.Errorf("got %v, want [%s]", got, a)
	}
}

func TestWalkGoFiles_SkipsVendorDir(t *testing.T) {
	root := t.TempDir()
	a := writeFile(t, root, "a.go", goStub)
	writeFile(t, root, "vendor/pkg/x.go", goStub)

	got, err := WalkGoFiles(root)
	if err != nil {
		t.Fatalf("WalkGoFiles: %v", err)
	}
	if !reflect.DeepEqual(got, []string{a}) {
		t.Errorf("got %v, want [%s]", got, a)
	}
}

func TestWalkGoFiles_SkipsDotDirs(t *testing.T) {
	root := t.TempDir()
	a := writeFile(t, root, "a.go", goStub)
	writeFile(t, root, ".git/hooks/x.go", goStub)
	writeFile(t, root, ".idea/y.go", goStub)
	writeFile(t, root, ".vscode/z.go", goStub)
	writeFile(t, root, ".hidden/q.go", goStub)

	got, err := WalkGoFiles(root)
	if err != nil {
		t.Fatalf("WalkGoFiles: %v", err)
	}
	if !reflect.DeepEqual(got, []string{a}) {
		t.Errorf("got %v, want [%s]", got, a)
	}
}

func TestWalkGoFiles_SkipsUnderscoreDirs(t *testing.T) {
	root := t.TempDir()
	a := writeFile(t, root, "a.go", goStub)
	writeFile(t, root, "_generated/x.go", goStub)

	got, err := WalkGoFiles(root)
	if err != nil {
		t.Fatalf("WalkGoFiles: %v", err)
	}
	if !reflect.DeepEqual(got, []string{a}) {
		t.Errorf("got %v, want [%s]", got, a)
	}
}

func TestWalkGoFiles_SkipsTestdataDir(t *testing.T) {
	root := t.TempDir()
	a := writeFile(t, root, "a.go", goStub)
	writeFile(t, root, "testdata/fixtures.go", goStub)
	writeFile(t, root, "sub/testdata/more.go", goStub)

	got, err := WalkGoFiles(root)
	if err != nil {
		t.Fatalf("WalkGoFiles: %v", err)
	}
	if !reflect.DeepEqual(got, []string{a}) {
		t.Errorf("got %v, want [%s]", got, a)
	}
}

func TestWalkGoFiles_SkipsUnderscoreFiles(t *testing.T) {
	root := t.TempDir()
	a := writeFile(t, root, "a.go", goStub)
	writeFile(t, root, "_ignored.go", goStub)

	got, err := WalkGoFiles(root)
	if err != nil {
		t.Fatalf("WalkGoFiles: %v", err)
	}
	if !reflect.DeepEqual(got, []string{a}) {
		t.Errorf("got %v, want [%s]", got, a)
	}
}

func TestWalkGoFiles_SkipsGeneratedFiles(t *testing.T) {
	root := t.TempDir()
	a := writeFile(t, root, "a.go", goStub)
	writeFile(t, root, "gen.go", "// Code generated by mocker; DO NOT EDIT.\npackage p\n")

	got, err := WalkGoFiles(root)
	if err != nil {
		t.Fatalf("WalkGoFiles: %v", err)
	}
	if !reflect.DeepEqual(got, []string{a}) {
		t.Errorf("got %v, want [%s]", got, a)
	}
}

func TestWalkGoFiles_NonGoFilesIgnored(t *testing.T) {
	root := t.TempDir()
	a := writeFile(t, root, "a.go", goStub)
	writeFile(t, root, "readme.md", "hi")
	writeFile(t, root, "data.json", "{}")
	writeFile(t, root, "notes.txt", "n")

	got, err := WalkGoFiles(root)
	if err != nil {
		t.Fatalf("WalkGoFiles: %v", err)
	}
	if !reflect.DeepEqual(got, []string{a}) {
		t.Errorf("got %v, want [%s]", got, a)
	}
}

func TestWalkGoFiles_DeterministicOrder(t *testing.T) {
	root := t.TempDir()
	// Write in intentionally non-sorted order; the walker must still return
	// sorted output.
	paths := []string{
		writeFile(t, root, "z.go", goStub),
		writeFile(t, root, "a.go", goStub),
		writeFile(t, root, "m.go", goStub),
		writeFile(t, root, "b/c.go", goStub),
		writeFile(t, root, "b/a.go", goStub),
	}
	got, err := WalkGoFiles(root)
	if err != nil {
		t.Fatalf("WalkGoFiles: %v", err)
	}
	if len(got) != len(paths) {
		t.Fatalf("got %d files, want %d (%v)", len(got), len(paths), got)
	}
	if !sort.StringsAreSorted(got) {
		t.Errorf("walk output is not sorted ascending: %v", got)
	}
}

func TestWalkGoFiles_MissingRootReturnsError(t *testing.T) {
	root := filepath.Join(t.TempDir(), "does-not-exist")
	_, err := WalkGoFiles(root)
	if err == nil {
		t.Fatalf("expected error for missing root, got nil")
	}
}

func TestWalkGoFiles_EmptyDirReturnsEmpty(t *testing.T) {
	root := t.TempDir()
	got, err := WalkGoFiles(root)
	if err != nil {
		t.Fatalf("WalkGoFiles: %v", err)
	}
	if len(got) != 0 {
		t.Errorf("want empty slice, got %v", got)
	}
}

// TestWalkGoFiles_RootNamedTestdataNotSkipped guards the root-dir edge case:
// passing testdata/ (or any otherwise-excluded basename) directly as root
// must still surface its .go files — we only filter *descendant* dirs.
func TestWalkGoFiles_RootNamedTestdataNotSkipped(t *testing.T) {
	parent := t.TempDir()
	root := filepath.Join(parent, "testdata")
	if err := os.Mkdir(root, 0o755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	a := writeFile(t, root, "a.go", goStub)
	got, err := WalkGoFiles(root)
	if err != nil {
		t.Fatalf("WalkGoFiles: %v", err)
	}
	if !reflect.DeepEqual(got, []string{a}) {
		t.Errorf("got %v, want [%s]", got, a)
	}
}

func TestIsGenerated_DetectsMarker(t *testing.T) {
	root := t.TempDir()
	path := writeFile(t, root, "gen.go", "// Code generated by mocker; DO NOT EDIT.\npackage p\n")
	got, err := IsGenerated(path)
	if err != nil {
		t.Fatalf("IsGenerated: %v", err)
	}
	if !got {
		t.Errorf("expected IsGenerated=true for canonical marker")
	}
}

func TestIsGenerated_MissingMarker(t *testing.T) {
	root := t.TempDir()
	path := writeFile(t, root, "plain.go", "package p\n// not a generated marker\n")
	got, err := IsGenerated(path)
	if err != nil {
		t.Fatalf("IsGenerated: %v", err)
	}
	if got {
		t.Errorf("expected IsGenerated=false for plain file")
	}
}

func TestIsGenerated_MarkerBeyondLineCap(t *testing.T) {
	root := t.TempDir()
	var body string
	for i := 0; i < 50; i++ {
		body += "// filler\n"
	}
	body += "// Code generated by x; DO NOT EDIT.\npackage p\n"
	path := writeFile(t, root, "late.go", body)
	got, err := IsGenerated(path)
	if err != nil {
		t.Fatalf("IsGenerated: %v", err)
	}
	if got {
		t.Errorf("marker past the 20-line cap should not be detected")
	}
}

// TestWalkGoFiles_NestedGitSkipped pins that a .git directory buried several
// levels below root (git-submodule layout) is skipped by basename just like
// a top-level .git — the walker must not descend into foreign repo metadata
// anywhere in the tree.
func TestWalkGoFiles_NestedGitSkipped(t *testing.T) {
	root := t.TempDir()
	a := writeFile(t, root, "a.go", goStub)
	writeFile(t, root, "modules/foo/.git/x.go", goStub)

	got, err := WalkGoFiles(root)
	if err != nil {
		t.Fatalf("WalkGoFiles: %v", err)
	}
	if !reflect.DeepEqual(got, []string{a}) {
		t.Errorf("got %v, want [%s]", got, a)
	}
}

// TestWalkGoFiles_DirSymlinkNotFollowed pins the "we inherit filepath.WalkDir's
// no-symlink-follow default" behaviour: a symlinked directory is visited as a
// non-dir entry and its contents are unreachable via the symlink path.
func TestWalkGoFiles_DirSymlinkNotFollowed(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("symlinks on Windows require elevated privileges")
	}
	root := t.TempDir()
	targetDir := filepath.Join(root, "target")
	targetFile := writeFile(t, root, "target/target.go", goStub)
	if err := os.Symlink(targetDir, filepath.Join(root, "link")); err != nil {
		t.Fatalf("symlink: %v", err)
	}

	got, err := WalkGoFiles(root)
	if err != nil {
		t.Fatalf("WalkGoFiles: %v", err)
	}
	// We expect exactly the real path, not the symlinked one.
	if !reflect.DeepEqual(got, []string{targetFile}) {
		t.Errorf("got %v, want [%s] (symlink should not be followed)", got, targetFile)
	}
}

// TestWalkGoFiles_UnreadableDirSkippedNotFatal pins the W2 fix: a chmod-0
// subdirectory must not abort the whole walk — SkipDir'd silently while
// readable siblings keep producing results.
func TestWalkGoFiles_UnreadableDirSkippedNotFatal(t *testing.T) {
	if os.Geteuid() == 0 {
		t.Skip("root bypasses chmod — cannot exercise permission-denied path")
	}
	root := t.TempDir()
	a := writeFile(t, root, "a.go", goStub)
	locked := filepath.Join(root, "locked")
	writeFile(t, root, "locked/b.go", goStub)
	if err := os.Chmod(locked, 0o000); err != nil {
		t.Fatalf("chmod locked: %v", err)
	}
	// Restore permissions so t.TempDir's cleanup can remove the directory.
	defer os.Chmod(locked, 0o755)

	got, err := WalkGoFiles(root)
	if err != nil {
		t.Fatalf("WalkGoFiles returned error for unreadable subdir (want nil): %v", err)
	}
	if !reflect.DeepEqual(got, []string{a}) {
		t.Errorf("got %v, want [%s] (locked subdir should be skipped silently)", got, a)
	}
}

// TestWalkGoFiles_UnreadableFileReturnsError pins that file-level I/O failures
// still surface — W2 only relaxes directory-level errors, not file reads.
func TestWalkGoFiles_UnreadableFileReturnsError(t *testing.T) {
	if os.Geteuid() == 0 {
		t.Skip("root bypasses chmod — cannot exercise permission-denied path")
	}
	root := t.TempDir()
	bad := writeFile(t, root, "bad.go", goStub)
	if err := os.Chmod(bad, 0o000); err != nil {
		t.Fatalf("chmod bad: %v", err)
	}
	// Restore permissions so t.TempDir's cleanup can remove the file.
	defer os.Chmod(bad, 0o644)

	_, err := WalkGoFiles(root)
	if err == nil {
		t.Fatalf("expected error for unreadable .go file, got nil")
	}
}

// TestIsGenerated_MarkerInsideLineCap pins that a marker appearing within the
// 20-line scan window (but not on line 1) is still detected — off-by-one
// regression guard for maxGeneratedScanLines.
func TestIsGenerated_MarkerInsideLineCap(t *testing.T) {
	root := t.TempDir()
	var body string
	for i := 0; i < 10; i++ {
		body += "// filler\n"
	}
	body += "// Code generated by x; DO NOT EDIT.\npackage p\n"
	path := writeFile(t, root, "mid.go", body)
	got, err := IsGenerated(path)
	if err != nil {
		t.Fatalf("IsGenerated: %v", err)
	}
	if !got {
		t.Errorf("marker on line 11 (within 20-line cap) should be detected")
	}
}

// TestIsGenerated_RejectsLookalikes pins the four strict regex invariants
// (start-anchor, `// ` prefix, exact casing, trailing `DO NOT EDIT.`). Any
// relaxation — case-insensitive flag, (?m) without ^, TrimSpace — would
// silently hide real files and this test would catch it.
func TestIsGenerated_RejectsLookalikes(t *testing.T) {
	cases := []struct {
		name, body string
	}{
		{"case mismatch", "// CODE GENERATED by x; DO NOT EDIT.\n"},
		{"triple slash", "/// Code generated by x; DO NOT EDIT.\n"},
		{"leading whitespace", "  // Code generated by x; DO NOT EDIT.\n"},
		{"missing do-not-edit", "// Code generated by x; autogen.\n"},
		{"no space after slashes", "//Code generated by x; DO NOT EDIT.\n"},
	}
	root := t.TempDir()
	for i, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			path := writeFile(t, root, filepath.Join("case", "c"+string(rune('a'+i))+".go"), tc.body)
			got, err := IsGenerated(path)
			if err != nil {
				t.Fatalf("IsGenerated: %v", err)
			}
			if got {
				t.Errorf("lookalike %q should NOT match the canonical marker", tc.body)
			}
		})
	}
}

// TestIsGenerated_MissingFileReturnsError pins the error-propagation contract
// for os.Open failures — a missing path must surface as non-nil error so the
// walker can decide whether to propagate.
func TestIsGenerated_MissingFileReturnsError(t *testing.T) {
	_, err := IsGenerated(filepath.Join(t.TempDir(), "does-not-exist.go"))
	if err == nil {
		t.Fatalf("expected error for missing file, got nil")
	}
}

// TestIsGenerated_EmptyFile pins the degenerate case: an empty file has no
// lines to scan, so Scan() returns false immediately and we report (false, nil).
func TestIsGenerated_EmptyFile(t *testing.T) {
	root := t.TempDir()
	path := writeFile(t, root, "empty.go", "")
	got, err := IsGenerated(path)
	if err != nil {
		t.Fatalf("IsGenerated: %v", err)
	}
	if got {
		t.Errorf("empty file should not be reported as generated")
	}
}

// TestIsGenerated_GiantSingleLineDoesNotError pins the W1 fix: a 70 KiB
// single-line file triggers bufio.ErrTooLong inside Scanner, which we swallow
// and treat as "not generated". Regression guard against a revert that would
// abort the whole walk on one pathological file.
func TestIsGenerated_GiantSingleLineDoesNotError(t *testing.T) {
	root := t.TempDir()
	// 70 KiB of 'a' with no newline — exceeds maxGeneratedScanBytes (64 KiB),
	// forces Scanner to return ErrTooLong.
	body := strings.Repeat("a", 70*1024)
	path := writeFile(t, root, "giant.go", body)
	got, err := IsGenerated(path)
	if err != nil {
		t.Fatalf("IsGenerated should swallow bufio.ErrTooLong, got error: %v", err)
	}
	if got {
		t.Errorf("giant single-line file has no marker, should report false")
	}
}
